FROM rust:latest
RUN apt-get update && apt-get install -y libclang-dev && rm -rf /var/lib/apt/lists/*
RUN rustup component add rustfmt
RUN cargo install bindgen-cli
WORKDIR /work
ENTRYPOINT ["bindgen"]
